version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: quickfund-backend:local
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./quickFund
    image: quickfund-frontend:local
    env_file:
      - ./quickFund/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quickfund
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

volumes:
  pgdata: 